Running docker on linux
worknenjoy/gitpay pull request #844
Opened 2021-07-09 02:35 UTC by adelmojnr

## Description

> 

## Changes

- Running docker on linux.

## 842

> Closes #000

## Impacted Area

> Main page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue
- docker-compose -f docker-compose-linux.yml up

## Before
![image](https://user-images.githubusercontent.com/20758899/125014814-b9879300-e044-11eb-8b75-9851e48751b7.png)

## After
![image](https://user-images.githubusercontent.com/20758899/125015060-24d16500-e045-11eb-92ea-19eb9acfe186.png)

2021-07-09 10:07 UTC, alexanmtz requested changes
@adelmojnr great, for now, I think this can work, and maybe we need to have docker executing in one file, and not a separate Linux file, but this can work to not block this setup

I just need that you remove from the your commit the `package` files, so you need to run in your local and push:
`git checkout master -- frontend/package-lock.json`
`git checkout master -- frontend/package.json`

Then commit the changes to back these files from the master branch, cause they're not part of the commit, considering that you're not adding any library to the project

2021-07-10 03:22 UTC, adelmojnr reviewed
I solved what you asked.

2021-07-12 13:32 UTC, alexanmtz commented
Great @adelmojnr 👍

2021-07-12 13:32 UTC, alexanmtz approved these changes

2021-07-12 13:32 UTC, merged