Issue#886 - Update issue imported from Gitpay after receive an invoice paid webhook
worknenjoy/gitpay pull request #889
Opened 2022-04-04 03:07 UTC by VictorAlessander

## Description

> Feature to support orders created and paid from funding accounts to be recognized and processed correctly by Gitpay.

## Changes

- webhooks
- user model
- assign actions modal

## Issue

> Closes #886 

## Impacted Area

> Assign actions modal
> User model
> Webhook

## Steps to test (TODO)

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / log user
- Create Task
- Other steps

## Before (TODO)
> Screenshot from the state before

## After (TODO)
> Screenshot from the state after your Pull Request

2022-04-11 02:53 UTC, VictorAlessander commented
@alexanmtz 
Build failed because probably it's missing the seed-test command to run.

2022-04-11 10:04 UTC, alexanmtz requested changes

2022-04-12 02:21 UTC, VictorAlessander commented on modules/app/controllers/webhook.js
> +        })
Done. Let me know if it's good now.

2022-04-19 13:19 UTC, alexanmtz requested changes
Great @VictorAlessander , now it's so much better now

We're still missing one of the requirements before we can move on:

_Subtask 1) Change this screen to have an email field, if I wish to pass another other than mine, because we need to pass another customer other than the one is sending_

we need to have an input with an email that when specified we create an order with that email rather than the current user, if is empty (or we can have a checkbox) we should get the current user

Can you do this adjustments?

2022-04-19 20:57 UTC, VictorAlessander commented
> Great @VictorAlessander , now it's so much better now
> 
> We're still missing one of the requirements before we can move on:
> 
> _Subtask 1) Change this screen to have an email field, if I wish to pass another other than mine, because we need to pass another customer other than the one is sending_
> 
> we need to have an input with an email that when specified we create an order with that email rather than the current user, if is empty (or we can have a checkbox) we should get the current user
> 
> Can you do this adjustments?

Oh, sorry, I forgot that. Sure, going to implement.

2022-04-19 21:15 UTC, VictorAlessander commented
@alexanmtz Ok, it's done. Let me know if is needed to do anything else.

2022-04-20 13:40 UTC, merged